title: Loose Screws
description: Rantings and musings

url: http://blog.5digits.org
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "page:num/"
permalink: :year/:month/:day/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
kramdown:
  math_engine: katex
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /
#    - title: About
#      url: /about
#    - title: Contact
#      url: /contact

social:
    github: kmaglione
    twitter: NoMiddleGears
    email: maglione.k@gmail.com
    linkedin: kmaglione
    # facebook: kmaglione
    # youtube: kmaglione
    # tumblr: kmaglione

# google_analytics: "UA-58263416-1"

disqus:
    shortname: loosescrews
